### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by chris35469** [viewstools/morph#154]
After running 

`views-morph . --watch --as react-native`

I get the following error.

M Feed TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1456:5)
    at isView (/usr/local/lib/node_modules/@viewstools/morph/watch.js:41:26)
    at getImportFileName (/usr/local/lib/node_modules/@viewstools/morph/watch.js:151:11)
    at /usr/local/lib/node_modules/@viewstools/morph/watch.js:242:28
    at finalGetImport (/usr/local/lib/node_modules/@viewstools/morph/lib.js:3072:31)
    at /usr/local/lib/node_modules/@viewstools/morph/lib.js:2127:25
    at Array.forEach (<anonymous>)
    at getDependencies (/usr/local/lib/node_modules/@viewstools/morph/lib.js:2119:21)
    at toComponent (/usr/local/lib/node_modules/@viewstools/morph/lib.js:2285:93)

The following command seems to make the top level file. However, it does not generate imported components. 

`views-morph Feed.view --as react-native > Feed.view.js`

'f' on line watch.js:41:26 seems to not be defined. Should I run a different command to generate react-native code? 

node: v8.11.3 
System: macOS Sierra

**Comment by amymc** [comment]
Hi @chris35469, 

Thanks for trying out Views! 

`views-morph . --watch --as react-native` is correct. 

It sounds like `Feed.view` is trying to import a component that doesn’t yet exist. What does your `Feed.view` file look like?

**Comment by chris35469** [comment]
Thanks! That fixed it. I removed a few components that were not defined. Removing them fixed my error. Thanks!

**Comment by amymc** [comment]
Cool! No worries. 🙂
